print ("[BOT] Mechanism: Hola")
ans = input()
print ("[BOT] Mechanism: Cual es tu nombre?")
name = input()
print = ("[BOT] Mechanism: Oh, Genial Hola" + name + ".")
ans = input ()
print ("[BOT] Mechanism: Como estas?" + name + "?")
asn = input()
print ("[BOT] Mechanism: Estoy funcionando correctamente, gracias por preocuparte!.")
ans = input()
print  ("[BOT] Mechanism: increíble!.")
ans = input ()
print = ("[BOT] Mechanism: quieres contarme algo?")
ans = input()
print = ("[BOT] Mechanism: interesante, tristemente no puedo sentir nada ya que soy un ChatBot")
ans = input()
print  = ("[BOT] Mechanism: mola")


